---
config:
  theme: 'base'
  themeVariables:
    primaryColor: '#eaf6e0'
    secondaryColor: '#eaf6e0'
    background: white
---

flowchart LR

    A["User<br/>Message"] -.-> B["Summarization"] -.-> C["PatchToolCalls"] --> D["Model"] --> E["TodoList"]

    E --> F["Filesystem"]
    E --> K["Execute"]
    E --> J["Tools/Skills"]
    J -.->|"task"| G["SubAgent"]

    F --> H["HITL<br/>(optional)"]
    K --> H
    J --> H
    G --> H

    H -->|"loop"| C

    classDef node fill:#fff,stroke:#444,stroke-width:2px,color:#222;
    classDef cluster fill:#eaf6e0,stroke:#76b900,stroke-width:3px,color:#111,rounded corners,shadow;
